---
title: "Weight Training Analysis"
author: "Alex Fennell"
output: 
    html_document:
    toc: true
self_contained: true
github_document:
    toc: true
---
    
```{r libraries,message=FALSE,warning=FALSE}
library(randomForest)
library(e1071)
library(parallel)
library(MLmetrics)
library(foreach)
library(doParallel)
library(caret)
library(dplyr)
```


```{r data loading}
#train data location
fileurl<-"https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
if (!file.exists("fittrain.csv")){
    download.file(fileurl,"fittrain.csv",method="curl")
}
#test data location
fileurl<-"https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
if (!file.exists("fittest.csv")){
    download.file(fileurl,"fittest.csv",method="curl")
}

fit_train<-read.csv("fittrain.csv",na.strings = c("NA",""))
fit_test<-read.csv("fittest.csv",na.strings = c("NA",""))
```


```{r examine missing data}
colSums(is.na(fit_train))
```

Given a good number of these variables are columns of missing values, I will go 
ahead and remove these.

```{r remove missing values}
threshold=.95
trainfilt<-fit_train[,colSums(is.na(fit_train))<(nrow(fit_train)*threshold)]
testfilt<-fit_test[,colSums(is.na(fit_test))<(nrow(fit_test)*threshold)]
```

Remove columns that contain time series data. I will only be using the data from the
accelerometers.

```{r remove timeseries data}
trainfilt<-trainfilt[,-c(1,2,3,4,5,6,7)]
testfilt<-testfilt[,-c(1,2,3,4,5,6,7)]

trainfilt$classe<-as.factor(trainfilt$classe)
```

```{r Find multicolinearity}
library(Hmisc)
cormat<-trainfilt%>%
    select_if(is.numeric)%>%
    as.matrix()%>%
    rcorr(type='spearman')
highcor<-findCorrelation(cormat$r,cutoff = 0.75)
colnames(cormat$r[highcor,highcor])
```

```{r determine near zero variance}
nsv<-nearZeroVar(trainfilt,saveMetrics = TRUE)
sum(nsv$zeroVar==TRUE)
sum(nsv$nzv==TRUE)

```

```{r prepare data for modelling}
samp<-createDataPartition(y=trainfilt$classe,p=.8,list = FALSE)
training<-trainfilt[samp,]
validation<-trainfilt[-samp,]
```


```{r random forest model fit,cache=TRUE}

cluster<-makeCluster(detectCores()-6) # leave some cores to do other things
registerDoParallel(cluster)

control<-trainControl(method='repeatedcv',
                      number=10,
                      repeats = 3,
                      classProbs = TRUE,
                      summaryFunction = multiClassSummary,
                      allowParallel = TRUE,
                      savePredictions = TRUE,
                      search='random',
                      verboseIter = TRUE)
trainpre<-preProcess(training,method=c('center','scale','pca'),thresh=.95)
trainpca<-predict(trainpre,training)
valpca<-predict(trainpre,validation)
testpca<-predict(trainpre,testfilt)

testpca<-predict(trainpre,test)
    rfmod<-train(classe~.,
                 data=trainpca,
                 method='rf',
                 ntree=250,
                 tuneLength=10,
                 verbose=TRUE,
                 metric='Accuracy',
                 trControl=control)

stopCluster(cluster)
registerDoSEQ()
```

```{r vip plot}
library(vip)
vip(rfmod)
```

```{r examination of pc 15}
a<-head(sort(trainpre$rotation[,15]),5)
b<-head(sort(trainpre$rotation[,15],decreasing=TRUE),5)
data.frame(PCAval=c(a,b))
```

```{r confusion matrix cross val holdout set}
confusionMatrix(rfmod)
```


```{r confusion matrix validation data set}
confusionMatrix(predict(rfmod,valpca),valpca$classe)
```



```{r model predictions test set}
rfpred<-predict(rfmod,testpca)
rfpred
```